apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-marks-dev
spec:
  secretName: wildcard-marks-dev
  renewBefore: 240h
  dnsNames:
  - '*.marks.dev'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer