name: marks.dev Build and Release Pipeline
on:
  push:
    branches: [ 'main' ]

jobs:
  Build-Site-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get Git Short Shahash
        id: new_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check outputs
        run: echo ${{ steps.new_sha.outputs.sha_short }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            eaglerock/marks.dev:latest
            eaglerock/marks.dev:${{ steps.new_sha.outputs.sha_short }}

  Publish-HLC-Site:
    runs-on: ubuntu-latest
    env:
      RELEASE_REPO: eaglerock1337/happy-little-cloud
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: $RELEASE_REPO
          token: ${{ secrets.HLC_GITHUB_TOKEN }}
      - name: Get Old Version from Chart yaml
        id: old_sha
        run: echo "sha_short=$(grep appVersion Chart.yaml | cut -f2 -d'"')" >> $GITHUB_OUTPUT
      - name: Swap Git Tag in Chart.yaml
        run: sed -i /appVersion/s/${{ steps.old_sha.outputs.sha_short }}/${{ steps.new_sha.output.sha_short }}/ Chart.yaml
      - name: Commit New Version to GitHub
        run: git commit -am "Update marks.dev site to use ${{ steps.new_sha.output.sha_short }} tag" && git push
